///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CastCharacterLinksSelf {
/*
{
  "href": "https://api.tvmaze.com/characters/1"
} 
*/

  String? href;

  CastCharacterLinksSelf({
    this.href,
  });
  CastCharacterLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class CastCharacterLinks {
/*
{
  "self": {
    "href": "https://api.tvmaze.com/characters/1"
  }
} 
*/

  CastCharacterLinksSelf? self;

  CastCharacterLinks({
    this.self,
  });
  CastCharacterLinks.fromJson(Map<String, dynamic> json) {
    self = (json['self'] != null)
        ? CastCharacterLinksSelf.fromJson(json['self'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (self != null) {
      data['self'] = self!.toJson();
    }
    return data;
  }
}

class CastCharacterImage {
/*
{
  "medium": "https://static.tvmaze.com/uploads/images/medium_portrait/0/3.jpg",
  "original": "https://static.tvmaze.com/uploads/images/original_untouched/0/3.jpg"
} 
*/

  String? medium;
  String? original;

  CastCharacterImage({
    this.medium,
    this.original,
  });
  CastCharacterImage.fromJson(Map<String, dynamic> json) {
    medium = json['medium']?.toString();
    original = json['original']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['medium'] = medium;
    data['original'] = original;
    return data;
  }
}

class CastCharacter {
/*
{
  "id": 1,
  "url": "https://www.tvmaze.com/characters/1/under-the-dome-dale-barbie-barbara",
  "name": "Dale \"Barbie\" Barbara",
  "image": {
    "medium": "https://static.tvmaze.com/uploads/images/medium_portrait/0/3.jpg",
    "original": "https://static.tvmaze.com/uploads/images/original_untouched/0/3.jpg"
  },
  "_links": {
    "self": {
      "href": "https://api.tvmaze.com/characters/1"
    }
  }
} 
*/

  int? id;
  String? url;
  String? name;
  CastCharacterImage? image;
  CastCharacterLinks? Links;

  CastCharacter({
    this.id,
    this.url,
    this.name,
    this.image,
    this.Links,
  });
  CastCharacter.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    url = json['url']?.toString();
    name = json['name']?.toString();
    image = (json['image'] != null)
        ? CastCharacterImage.fromJson(json['image'])
        : null;
    Links = (json['_links'] != null)
        ? CastCharacterLinks.fromJson(json['_links'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    data['name'] = name;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    if (Links != null) {
      data['_links'] = Links!.toJson();
    }
    return data;
  }
}

class CastPersonLinksSelf {
/*
{
  "href": "https://api.tvmaze.com/people/1"
} 
*/

  String? href;

  CastPersonLinksSelf({
    this.href,
  });
  CastPersonLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class CastPersonLinks {
/*
{
  "self": {
    "href": "https://api.tvmaze.com/people/1"
  }
} 
*/

  CastPersonLinksSelf? self;

  CastPersonLinks({
    this.self,
  });
  CastPersonLinks.fromJson(Map<String, dynamic> json) {
    self = (json['self'] != null)
        ? CastPersonLinksSelf.fromJson(json['self'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (self != null) {
      data['self'] = self!.toJson();
    }
    return data;
  }
}

class CastPersonImage {
/*
{
  "medium": "https://static.tvmaze.com/uploads/images/medium_portrait/0/1815.jpg",
  "original": "https://static.tvmaze.com/uploads/images/original_untouched/0/1815.jpg"
} 
*/

  String? medium;
  String? original;

  CastPersonImage({
    this.medium,
    this.original,
  });
  CastPersonImage.fromJson(Map<String, dynamic> json) {
    medium = json['medium']?.toString();
    original = json['original']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['medium'] = medium;
    data['original'] = original;
    return data;
  }
}

class CastPersonCountry {
/*
{
  "name": "United States",
  "code": "US",
  "timezone": "America/New_York"
} 
*/

  String? name;
  String? code;
  String? timezone;

  CastPersonCountry({
    this.name,
    this.code,
    this.timezone,
  });
  CastPersonCountry.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    code = json['code']?.toString();
    timezone = json['timezone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['code'] = code;
    data['timezone'] = timezone;
    return data;
  }
}

class CastPerson {
/*
{
  "id": 1,
  "url": "https://www.tvmaze.com/people/1/mike-vogel",
  "name": "Mike Vogel",
  "country": {
    "name": "United States",
    "code": "US",
    "timezone": "America/New_York"
  },
  "birthday": "1979-07-17",
  "deathday": null,
  "gender": "Male",
  "image": {
    "medium": "https://static.tvmaze.com/uploads/images/medium_portrait/0/1815.jpg",
    "original": "https://static.tvmaze.com/uploads/images/original_untouched/0/1815.jpg"
  },
  "updated": 1634211735,
  "_links": {
    "self": {
      "href": "https://api.tvmaze.com/people/1"
    }
  }
} 
*/

  int? id;
  String? url;
  String? name;
  CastPersonCountry? country;
  String? birthday;
  String? deathday;
  String? gender;
  CastPersonImage? image;
  int? updated;
  CastPersonLinks? Links;

  CastPerson({
    this.id,
    this.url,
    this.name,
    this.country,
    this.birthday,
    this.deathday,
    this.gender,
    this.image,
    this.updated,
    this.Links,
  });
  CastPerson.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    url = json['url']?.toString();
    name = json['name']?.toString();
    country = (json['country'] != null)
        ? CastPersonCountry.fromJson(json['country'])
        : null;
    birthday = json['birthday']?.toString();
    deathday = json['deathday']?.toString();
    gender = json['gender']?.toString();
    image = (json['image'] != null)
        ? CastPersonImage.fromJson(json['image'])
        : null;
    updated = json['updated']?.toInt();
    Links = (json['_links'] != null)
        ? CastPersonLinks.fromJson(json['_links'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    data['name'] = name;
    if (country != null) {
      data['country'] = country!.toJson();
    }
    data['birthday'] = birthday;
    data['deathday'] = deathday;
    data['gender'] = gender;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    data['updated'] = updated;
    if (Links != null) {
      data['_links'] = Links!.toJson();
    }
    return data;
  }
}

class Cast {
/*
{
  "person": {
    "id": 1,
    "url": "https://www.tvmaze.com/people/1/mike-vogel",
    "name": "Mike Vogel",
    "country": {
      "name": "United States",
      "code": "US",
      "timezone": "America/New_York"
    },
    "birthday": "1979-07-17",
    "deathday": null,
    "gender": "Male",
    "image": {
      "medium": "https://static.tvmaze.com/uploads/images/medium_portrait/0/1815.jpg",
      "original": "https://static.tvmaze.com/uploads/images/original_untouched/0/1815.jpg"
    },
    "updated": 1634211735,
    "_links": {
      "self": {
        "href": "https://api.tvmaze.com/people/1"
      }
    }
  },
  "character": {
    "id": 1,
    "url": "https://www.tvmaze.com/characters/1/under-the-dome-dale-barbie-barbara",
    "name": "Dale \"Barbie\" Barbara",
    "image": {
      "medium": "https://static.tvmaze.com/uploads/images/medium_portrait/0/3.jpg",
      "original": "https://static.tvmaze.com/uploads/images/original_untouched/0/3.jpg"
    },
    "_links": {
      "self": {
        "href": "https://api.tvmaze.com/characters/1"
      }
    }
  },
  "self": false,
  "voice": false
} 
*/

  CastPerson? person;
  CastCharacter? character;
  bool? self;
  bool? voice;

  Cast({
    this.person,
    this.character,
    this.self,
    this.voice,
  });
  Cast.fromJson(Map<String, dynamic> json) {
    person =
        (json['person'] != null) ? CastPerson.fromJson(json['person']) : null;
    character = (json['character'] != null)
        ? CastCharacter.fromJson(json['character'])
        : null;
    self = json['self'];
    voice = json['voice'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (person != null) {
      data['person'] = person!.toJson();
    }
    if (character != null) {
      data['character'] = character!.toJson();
    }
    data['self'] = self;
    data['voice'] = voice;
    return data;
  }
}
